// ひとまずそれぞれ記入して頭の_を消すこと

const DISCORD_WEBHOOK_URL_MOVIE = ''
const DISCORD_WEBHOOK_URL_LIVE = ''
const YOUTUBE_PLAYLIST_ID = ''
const YOUTUBE_API_KEY = ''

export {
  DISCORD_WEBHOOK_URL_MOVIE,
  DISCORD_WEBHOOK_URL_LIVE,
  YOUTUBE_PLAYLIST_ID,
  YOUTUBE_API_KEY,
}
