// ひとまずそれぞれ記入して頭の_を消すこと

const DISCORD_TOKEN = ""
const DISCORD_CLIENT_ID = ""
const DISCORD_CHANNEL_ID_MOVIE = ""
const DISCORD_CHANNEL_ID_LIVE = ""
const YOUTUBE_PLAYLIST_ID = ""
const YOUTUBE_API_KEY = ""

export { DISCORD_TOKEN, DISCORD_CLIENT_ID, DISCORD_CHANNEL_ID_MOVIE, DISCORD_CHANNEL_ID_LIVE, YOUTUBE_PLAYLIST_ID, YOUTUBE_API_KEY }